version: "3.3"
services:

  mangayukiii-spr:
    image: 'sh1rayuk1/mangayukiii-spr:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -DXmxlg
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mangayukiii
      POSTGRES_USER: mangayukiii
      POSTGRES_PASSWORD: mangayukiii