spring:
  datasource:
    url: jdbc:postgresql://localhost/mangayukiii
    driverClassName: org.postgresql.Driver
    username: mangayukiii
    password: mangayukiii

logging:
#  level:
#    root: DEBUG

    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

      springframework:
        web:
          client:
            RestTemplate: DEBUG
