name: CI Dev Pipeline
on:
  push:
    branches:
      - dev
# ------------------
# Application Values
# ------------------
env:
  SERVICE_NAME: mangayukiii
jobs:
  push_image:
    name: Compile code
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: |
            ${{ runner.os }}-maven
      - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: make push-docker
